on:
  push:
    branches: [main]
name: Publish Docker image
jobs:
  push_to_registry:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: use github repository
      run: echo 'repository ${{ github.repository }} ${{ github.sha }}'
    -
      name: build and push to docker
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository }}
        # registry: docker.pkg.github.com
        #file: ./Dockerfile
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}
