name: Publish Docker image
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: use github variables
      run: echo '${{ github.repository }} AND ${{ github.sha }}'
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}
    - name: ls of linode container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.LINODE_HOST }}
        username: ${{ secrets.LINODE_USERNAME }}
        # key: ${{ secrets.LINODE_SSHKEY }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.LINODE_PORT }}
        script: |
          whoami
          ls -l
