on:
  push:
    branches: [main]
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    -
      name: build and push to docker
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        # repository: ${{ github.repository }}
        context: ./
        file: ./Dockerfile
        push: true
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}